namespace SentinelRelay.Models;

public enum RelayChatType
{
    Say = 0,
    Yell = 1,
    Shout = 2,
    IncomingTell = 3,
    Party = 4,
    Alliance = 5,
    FreeCompany = 6,
    PvPTeam = 7,
    Linkshell1 = 8,
    Linkshell2 = 9,
    Linkshell3 = 10,
    Linkshell4 = 11,
    Linkshell5 = 12,
    Linkshell6 = 13,
    Linkshell7 = 14,
    Linkshell8 = 15,
    CrossWorldLinkshell1 = 16,
    CrossWorldLinkshell2 = 17,
    CrossWorldLinkshell3 = 18,
    CrossWorldLinkshell4 = 19,
    CrossWorldLinkshell5 = 20,
    CrossWorldLinkshell6 = 21,
    CrossWorldLinkshell7 = 22,
    CrossWorldLinkshell8 = 23,
    NoviceNetwork = 24,
    StandardEmote = 25,
    CustomEmote = 26,
    OutgoingTell = 27,
    CrossWorldParty = 28,
}
